"use strict";
(()=>{const A=SimApp;
const showMed=()=>A.$("showMedian").checked,showMean=()=>A.$("showMean").checked;
function centerIndex(){return A.clamp(Math.round(Number(A.$("centerPath").value)||1)-1,0,Math.max(0,A.state.paths.length-1));}
function updateCi(){const c=A.getConfidence(),lo=A.percentLabel(c.lowerQ),hi=A.percentLabel(c.upperQ),t=`${c.level}%区間 (${lo}–${hi})`;A.$("indexCiLegend").textContent=t;A.$("portfolioCiLegend").textContent=t;A.$("checkpointLowerHead").textContent=lo;A.$("checkpointUpperHead").textContent=hi;}
function styleToUi(){const s=A.style,map={styleCenterColor:"centerColor",styleCenterWidth:"centerWidth",styleCenterAlpha:"centerAlpha",styleBeforeColor:"beforeColor",styleAfterColor:"afterColor",styleNeighborWidth:"neighborWidth",styleNeighborAlpha1:"neighborAlpha1",styleNeighborAlpha2:"neighborAlpha2",styleMedianColor:"medianColor",styleMedianWidth:"medianWidth",styleMedianAlpha:"medianAlpha",styleMeanColor:"meanColor",styleMeanWidth:"meanWidth",styleMeanAlpha:"meanAlpha",styleCiColor:"ciColor",styleCiEdgeWidth:"ciEdgeWidth",styleCiFillAlpha:"ciFillAlpha",styleCiEdgeAlpha:"ciEdgeAlpha",stylePortfolioYCapMultiplier:"portfolioYCapMultiplier"};for(const[k,v]of Object.entries(map))A.$(k).value=s[v];}
function uiToStyle(){const n=id=>Number(A.$(id).value),v=id=>A.$(id).value;return{...A.style,centerColor:v("styleCenterColor"),centerWidth:n("styleCenterWidth"),centerAlpha:n("styleCenterAlpha"),beforeColor:v("styleBeforeColor"),afterColor:v("styleAfterColor"),neighborWidth:n("styleNeighborWidth"),neighborAlpha1:n("styleNeighborAlpha1"),neighborAlpha2:n("styleNeighborAlpha2"),medianColor:v("styleMedianColor"),medianWidth:n("styleMedianWidth"),medianAlpha:n("styleMedianAlpha"),meanColor:v("styleMeanColor"),meanWidth:n("styleMeanWidth"),meanAlpha:n("styleMeanAlpha"),ciColor:v("styleCiColor"),ciEdgeWidth:n("styleCiEdgeWidth"),ciFillAlpha:n("styleCiFillAlpha"),ciEdgeAlpha:n("styleCiEdgeAlpha"),portfolioYCapMultiplier:n("stylePortfolioYCapMultiplier")};}
A.drawIndexPaths=()=>{if(!A.ensureData())return;const sel=A.makeSelectedPathIndices(Number(A.$("centerPath").value),Number(A.$("neighborCount").value),A.state.paths.length);A.$("centerPath").value=sel.center+1;const series=sel.ids.map(i=>({values:A.state.paths[i],...A.pathStyle(i,sel)})),sum=A.computeIndexSummarySeries(),center=A.state.paths[sel.center];A.drawPathChart(A.$("indexPathsCanvas"),series,{xValues:A.state.steps,scaleMode:"log",band:{lower:sum.lower,upper:sum.upper},median:showMed()?sum.median:null,mean:showMean()?sum.mean:null,centerValues:center,tooltipId:"indexLineTooltip",valueLabel:"指数"});A.$("indexPathSelectionNote").textContent=`path_${sel.lo} ～ path_${sel.hi} / 中心 path_${sel.center}`;};
A.drawIndexHistogram=()=>{if(!A.ensureData())return;const t=A.clamp(Math.round(Number(A.$("indexDistStep").value)||0),0,A.state.steps.length-1);A.$("indexDistStep").value=t;const vals=A.getIndexDistributionAt(t),ci=centerIndex(),s=A.drawLogHistogram(A.$("indexHistCanvas"),vals,{showMedian:showMed(),showMean:showMean(),centerValue:A.state.paths[ci][t],tooltipId:"indexHistTooltip"});if(s){const c=A.getConfidence(),items=[[A.percentLabel(c.lowerQ),s.lower],["P25",s.p25],["Median",s.median],["Mean",s.mean],["P75",s.p75],[A.percentLabel(c.upperQ),s.upper]];A.$("indexStats").innerHTML=items.map(([k,v])=>`<div class="stat"><div class="k">${k}</div><div class="v">${A.numberLabel(v)}</div></div>`).join("");}};
A.drawPortfolioPaths=()=>{if(!A.state.portfolio)return;const sel=A.makeSelectedPathIndices(Number(A.$("centerPath").value),Number(A.$("neighborCount").value),A.state.paths.length),mode=A.$("portfolioViewMode").value,series=sel.ids.map(i=>({values:A.portfolioSeriesForMode(A.portfolioPath(A.state.paths[i]),mode),...A.pathStyle(i,sel)})),sum=A.computePortfolioSummarySeries(mode),last=sum.upper.length-1;let ref=null,scale=mode==="profit"?"symlog":"log",domain=null,label=mode==="value"?"積立額":mode==="profit"?"損益額":"投資元本比";if(mode==="value"){ref=Array.from(A.state.portfolio.principalByStep);domain={max:sum.upper[last]*A.style.portfolioYCapMultiplier};}else if(mode==="profit"){ref=Array(A.state.steps.length).fill(0);const cap=Math.max(Math.abs(sum.lower[last]),Math.abs(sum.upper[last]))*A.style.portfolioYCapMultiplier;domain={min:-cap,max:cap};}else{ref=Array(A.state.steps.length).fill(1);domain={max:sum.upper[last]*A.style.portfolioYCapMultiplier};}const centerVals=A.portfolioSeriesForMode(A.portfolioPath(A.state.paths[sel.center]),mode);A.drawPathChart(A.$("portfolioPathsCanvas"),series,{xValues:A.state.steps,scaleMode:scale,domainOriginal:domain,band:{lower:sum.lower,upper:sum.upper},median:showMed()?sum.median:null,mean:showMean()?sum.mean:null,reference:ref,centerValues:centerVals,tooltipId:"portfolioLineTooltip",valueLabel:label});A.$("portfolioPathSelectionNote").textContent=`中心 path_${sel.center} / 表示上限倍率 ${A.style.portfolioYCapMultiplier}`;};
A.drawPortfolioHistogram=()=>{if(!A.state.portfolio)return;const t=A.clamp(Math.round(Number(A.$("portfolioDistStep").value)||0),0,A.state.steps.length-1);A.$("portfolioDistStep").value=t;const vals=A.portfolioDistributionAt(t),ci=centerIndex(),centerVal=A.portfolioValueAt(A.state.paths[ci],t),s=A.drawLogHistogram(A.$("portfolioHistCanvas"),vals,{showMedian:showMed(),showMean:showMean(),centerValue:centerVal,tooltipId:"portfolioHistTooltip"});if(s){const c=A.getConfidence(),pr=A.state.portfolio.principalByStep[t],loss=vals.filter(v=>v<pr).length/vals.length,items=[["元本",pr],[A.percentLabel(c.lowerQ),s.lower],["Median",s.median],["Mean",s.mean],[A.percentLabel(c.upperQ),s.upper],["元本割れ",loss,"p"]];A.$("portfolioStats").innerHTML=items.map(([k,v,tp])=>`<div class="stat"><div class="k">${k}</div><div class="v">${tp==="p"?A.percentDisplay(v):A.numberLabel(v)}</div></div>`).join("");}};
A.refreshCheckpointTable=()=>{if(!A.state.portfolio)return;const idx=[...new Set(A.$("checkpointSteps").value.split(",").map(x=>Math.round(Number(x.trim()))).filter(Number.isFinite).map(x=>A.clamp(x,0,A.state.steps.length-1)))].sort((a,b)=>a-b),c=A.getConfidence();A.$("checkpointBody").innerHTML=idx.map(t=>{const s=A.summarize(A.portfolioDistributionAt(t),c.lowerQ,c.upperQ),p=A.state.portfolio.principalByStep[t];return`<tr><td>${A.state.steps[t]}</td><td>${A.numberLabel(p)}</td><td>${A.numberLabel(s.lower)}</td><td>${A.numberLabel(s.p25)}</td><td>${A.numberLabel(s.median)}</td><td>${A.numberLabel(s.mean)}</td><td>${A.numberLabel(s.p75)}</td><td>${A.numberLabel(s.upper)}</td></tr>`;}).join("");};
A.refreshAll=()=>{updateCi();if(A.state.paths.length){A.drawIndexPaths();A.drawIndexHistogram();}if(A.state.portfolio){A.drawPortfolioPaths();A.drawPortfolioHistogram();A.refreshCheckpointTable();}};
const dz=A.$("dropZone");dz.onclick=()=>A.$("fileInput").click();dz.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();A.$("fileInput").click();}};["dragenter","dragover"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add("drag")}));["dragleave","drop"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove("drag")}));dz.addEventListener("drop",e=>A.loadLocalFile(e.dataTransfer.files?.[0]));A.$("fileInput").onchange=e=>A.loadLocalFile(e.target.files?.[0]);
A.$("preparedDataBtn").onclick=async()=>{const p=A.$("preparedDataPanel");p.classList.toggle("hidden");A.$("preparedDataBtn").textContent=p.classList.contains("hidden")?"USE prepared data ▼":"USE prepared data ▲";if(!p.classList.contains("hidden")&&!A.state.preparedItems.length)await A.loadPreparedManifest();};A.$("loadPreparedDataBtn").onclick=A.loadPreparedCsv;A.$("refreshPreparedDataBtn").onclick=A.loadPreparedManifest;
A.$("centerPrevBtn").onclick=()=>{if(!A.state.paths.length)return;A.$("centerPath").value=Math.max(1,Number(A.$("centerPath").value)-1);A.refreshAll();};A.$("centerNextBtn").onclick=()=>{if(!A.state.paths.length)return;A.$("centerPath").value=Math.min(A.state.paths.length,Number(A.$("centerPath").value)+1);A.refreshAll();};
A.$("applyPathSettingsBtn").onclick=()=>{A.state.indexSummaryCache.clear();if(A.state.portfolio)A.state.portfolio.summaryCache.clear();A.refreshAll();};A.$("showMedian").onchange=A.refreshAll;A.$("showMean").onchange=A.refreshAll;
A.$("autoNormalizeDcaBtn").onclick=()=>{A.autoNormalizeDca();A.runPortfolio();};A.$("runPortfolioBtn").onclick=A.runPortfolio;A.$("intervalDays").onchange=()=>{if(A.state.steps.length)A.autoNormalizeDca();};
A.$("indexDistStep").onchange=A.drawIndexHistogram;A.$("portfolioDistStep").onchange=A.drawPortfolioHistogram;A.$("indexFinalBtn").onclick=()=>{if(A.state.steps.length){A.$("indexDistStep").value=A.state.steps.length-1;A.drawIndexHistogram();}};A.$("portfolioFinalBtn").onclick=()=>{if(A.state.steps.length){A.$("portfolioDistStep").value=A.state.steps.length-1;A.drawPortfolioHistogram();}};A.$("portfolioViewMode").onchange=A.drawPortfolioPaths;A.$("refreshCheckpointBtn").onclick=A.refreshCheckpointTable;
A.$("indexPathsCanvas").onclick=e=>A.handleLineClick(A.$("indexPathsCanvas"),e);A.$("portfolioPathsCanvas").onclick=e=>A.handleLineClick(A.$("portfolioPathsCanvas"),e);A.$("indexHistCanvas").onclick=e=>A.handleHistogramClick(A.$("indexHistCanvas"),e);A.$("portfolioHistCanvas").onclick=e=>A.handleHistogramClick(A.$("portfolioHistCanvas"),e);
A.$("openStyleSettingsBtn").onclick=()=>{styleToUi();A.$("styleSettingsPanel").classList.remove("hidden");};A.$("closeStyleSettingsBtn").onclick=()=>A.$("styleSettingsPanel").classList.add("hidden");A.$("saveStyleSettingsBtn").onclick=()=>{A.style=uiToStyle();A.saveJsonStorage(CONFIG.styleStorageKey,A.style);A.$("styleSettingsPanel").classList.add("hidden");A.refreshAll();};A.$("resetStyleSettingsBtn").onclick=()=>{A.style=structuredClone(DEFAULT_STYLE);A.saveJsonStorage(CONFIG.styleStorageKey,A.style);styleToUi();A.refreshAll();};
let rt;window.onresize=()=>{clearTimeout(rt);rt=setTimeout(A.refreshAll,130)};updateCi();styleToUi();
})();
