"use strict";
window.SimApp=window.SimApp||{};
(()=>{const A=window.SimApp;
A.$=id=>{const el=document.getElementById(id);if(!el)throw new Error(`UI element not found: #${id}`);return el;};
A.fmt=new Intl.NumberFormat("ja-JP",{maximumFractionDigits:6});
A.fmt0=new Intl.NumberFormat("ja-JP",{maximumFractionDigits:0});
A.clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
A.quantile=(a,q)=>{if(!a.length)return NaN;const p=(a.length-1)*q,b=Math.floor(p),r=p-b;return a[b+1]!==undefined?a[b]+r*(a[b+1]-a[b]):a[b];};
A.mean=a=>{let s=0,n=0;for(const v of a)if(Number.isFinite(v)){s+=v;n++;}return n?s/n:NaN;};
A.summarize=(arr,lq=.05,uq=.95)=>{const a=arr.filter(Number.isFinite).slice().sort((x,y)=>x-y);return{n:a.length,min:a[0],lower:A.quantile(a,lq),p25:A.quantile(a,.25),median:A.quantile(a,.5),mean:A.mean(a),p75:A.quantile(a,.75),upper:A.quantile(a,uq),max:a[a.length-1]};};
A.getConfidence=()=>{let level=Number(A.$("confidenceLevel").value);level=A.clamp(Number.isFinite(level)?level:90,50,99.9);A.$("confidenceLevel").value=level;const tail=(1-level/100)/2;return{level,lowerQ:tail,upperQ:1-tail};};
A.numberLabel=v=>{if(!Number.isFinite(v))return"—";const av=Math.abs(v);if(av>=100)return Math.round(v).toLocaleString("ja-JP");if(av>=1)return Number(v.toFixed(3)).toLocaleString("ja-JP");if(av===0)return"0";return Number(v.toPrecision(3)).toLocaleString("ja-JP");};
A.percentDisplay=p=>{const pct=100*p;return (pct<=10||pct>=90)?`${pct.toFixed(1)}%`:`${Math.round(pct)}%`;};
A.percentLabel=q=>{const p=q*100;return`P${Number.isInteger(p)?p:p.toFixed(2).replace(/0+$/,"").replace(/\.$/,"")}`;};
A.setMessage=(m,e=false)=>{const el=A.$("message");el.textContent=m;el.className=e?"message error":"message";};
A.resizeCanvas=canvas=>{const dpr=devicePixelRatio||1,r=canvas.getBoundingClientRect(),w=Math.max(320,Math.floor(r.width)),h=Math.max(220,Math.floor(r.height));if(canvas.width!==Math.floor(w*dpr)||canvas.height!==Math.floor(h*dpr)){canvas.width=Math.floor(w*dpr);canvas.height=Math.floor(h*dpr);}const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w,h};};
A.symlog=(v,lin=window.CONFIG.symlogLinearThreshold)=>Number.isFinite(v)?Math.sign(v)*Math.log10(1+Math.abs(v)/lin):NaN;
A.invSymlog=(y,lin=window.CONFIG.symlogLinearThreshold)=>Number.isFinite(y)?Math.sign(y)*lin*(10**Math.abs(y)-1):NaN;
A.makeSelectedPathIndices=(centerOneBased,n,total)=>{const center=A.clamp(Math.round(centerOneBased)-1,0,total-1),nn=A.clamp(Math.round(n)||0,0,CONFIG.maxNeighborPathsPerSide),lo=Math.max(0,center-nn),hi=Math.min(total-1,center+nn),ids=[];for(let i=lo;i<=hi;i++)ids.push(i);return{center,lo,hi,ids};};
A.pathStyle=(i,sel)=>{const s=A.style;if(i===sel.center)return{color:s.centerColor,alpha:s.centerAlpha,width:s.centerWidth};const dist=Math.abs(i-sel.center),maxDist=i<sel.center?Math.max(1,sel.center-sel.lo):Math.max(1,sel.hi-sel.center),t=maxDist<=1?0:(dist-1)/(maxDist-1),alpha=s.neighborAlpha1+(s.neighborAlpha2-s.neighborAlpha1)*A.clamp(t,0,1);return{color:i<sel.center?s.beforeColor:s.afterColor,alpha,width:s.neighborWidth};};
A.hexToRgb=hex=>{const h=hex.replace("#",""),n=parseInt(h.length===3?h.split("").map(x=>x+x).join(""):h,16);return[(n>>16)&255,(n>>8)&255,n&255];};
A.rgba=(hex,a)=>{const[r,g,b]=A.hexToRgb(hex);return`rgba(${r},${g},${b},${A.clamp(a,0,1)})`;};
A.loadJsonStorage=(k,f)=>{try{const r=localStorage.getItem(k);return r?{...structuredClone(f),...JSON.parse(r)}:structuredClone(f);}catch{return structuredClone(f);}};
A.saveJsonStorage=(k,o)=>{try{localStorage.setItem(k,JSON.stringify(o));}catch(e){console.warn(e);}};
A.roundSig=(x,sig=3)=>{if(!Number.isFinite(x)||x===0)return x;return Number(x.toPrecision(sig));};
A.style=A.loadJsonStorage(CONFIG.styleStorageKey,DEFAULT_STYLE);
})();
